// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEa3C1i5s92oVsLCNCrKG-MwVY48oVNc',
    appId: '1:359298820692:web:d79cf73b2a38286fe8dbc1',
    messagingSenderId: '359298820692',
    projectId: 'modern-muse-4c35a',
    authDomain: 'modern-muse-4c35a.firebaseapp.com',
    storageBucket: 'modern-muse-4c35a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2koMe2mlDbzmRWsvUscdnnN3TW9gr2M',
    appId: '1:359298820692:android:ad1c7f5edcdbe4c4e8dbc1',
    messagingSenderId: '359298820692',
    projectId: 'modern-muse-4c35a',
    storageBucket: 'modern-muse-4c35a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDug2Pr6F9Io_tNrV-SDPbW_IjZrwdQZbQ',
    appId: '1:359298820692:ios:07db83ca08f86bfbe8dbc1',
    messagingSenderId: '359298820692',
    projectId: 'modern-muse-4c35a',
    storageBucket: 'modern-muse-4c35a.appspot.com',
    iosClientId: '359298820692-34vhoc718p9eojvvvs8k4o7ho5o2osbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceflutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDug2Pr6F9Io_tNrV-SDPbW_IjZrwdQZbQ',
    appId: '1:359298820692:ios:07db83ca08f86bfbe8dbc1',
    messagingSenderId: '359298820692',
    projectId: 'modern-muse-4c35a',
    storageBucket: 'modern-muse-4c35a.appspot.com',
    iosClientId: '359298820692-34vhoc718p9eojvvvs8k4o7ho5o2osbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceflutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByEa3C1i5s92oVsLCNCrKG-MwVY48oVNc',
    appId: '1:359298820692:web:6133d90af7b250d7e8dbc1',
    messagingSenderId: '359298820692',
    projectId: 'modern-muse-4c35a',
    authDomain: 'modern-muse-4c35a.firebaseapp.com',
    storageBucket: 'modern-muse-4c35a.appspot.com',
  );

}